### ISSUE TITLE
the releases apk is unavailable

### ISSUE THREAD

**Issue by YouthLin** [WenhaoWu/BingWallpaper#1]
When I try to install the application, it goes like this:
![screenshot_2016-01-30-11-55-26](https://cloud.githubusercontent.com/assets/6056413/12693565/72f5b20c-c748-11e5-895b-ed0e85d29df5.png)

> Parse erorr
> There was a problem parsing the package

My phone:
Android 4.1.2
HuaWei G520-5000
512 RAM
Inner Storage 2GB
External storage 16GB

**Comment by WenhaoWu** [comment]
Hello thanks for trying.
At this moment the minSdkVersion is 19, which means only phones running android 4.4 and above can install the application.
One thing to keep in mind is that the current version consumes quite an amount of memory. For phones have memory lower than 1GB the OOM may appear.

**Comment by YouthLin** [comment]
Sorry to disturb you again, but I got something wrong once more.  
I have got a Android pad and it's Android version is 4.4.4, so I install this app.  
However, when I open the app it shows as below: 
![screenshot_2016-01-30-22-10-10](https://cloud.githubusercontent.com/assets/6056413/12696193/508a077e-c796-11e5-941b-c2296b61db14.png)

Why the image doesn't show...
And, the Settings page can't open.(When I touch Settings Menu nothing happened.

**Comment by YouthLin** [comment]
Maybe you can see this:
https://github.com/WenhaoWu/BingWallpaper/blob/master/app/src/main/java/wenhao/practice/bingwallpaper/Model_GetImages.java#L49

                                img_url = response.getJSONArray("images").getJSONObject(i).getString("url");
                                img_copy = response.getJSONArray("images").getJSONObject(i).getString("copyright");
                                img_date = response.getJSONArray("images").getJSONObject(i).getString("startdate");
                                img_url = img_url.replace("1920x1080","1080x1920");
                                /*HERE*/ realURL = "http://www.bing.com"+img_url;
                                result.add(new Object_Wallpaper(realURL, img_copy,img_date));

In my location, the Bing server returned json  data is like this:

<pre>{
    "images": [
        {
            "startdate": "20160129",
            "fullstartdate": "201601291600",
            "enddate": "20160130",
            /*HERE*/ 
           "url": "http://s.cn.bing.net/az/hprichbg/rb/HammockCypress_ZH-CN10587366950_1920x1080.jpg",
            "urlbase": "/az/hprichbg/rb/HammockCypress_ZH-CN10587366950",
            "copyright": "在古老柏树上搭起吊床露营 (© Mac Stone/Tandem Stills + Motion)",
            "copyrightlink": "http://www.bing.com/search?q=%E9%9C%B2%E8%90%A5&form=hpcapt&mkt=zh-cn",
            "wp": true,
            "hsh": "88f11f28cd9b45328a23bec2dd0ca1e9",
            "drk": 1,
            "top": 1,
            "bot": 1,
            "hs": [],
            "msg": [
                {
                    "title": "今日图片故事",
                    "link": "http://www.bing.com/search?q=%E9%9C%B2%E8%90%A5&FORM=pgbar1&mkt=zh-cn",
                    "text": "露营"
                }
            ]
        }
    ],
    "tooltips": {
        "loading": "正在加载...",
        "previous": "上一页",
        "next": "下一页",
        "walle": "此图片不能下载用作壁纸。",
        "walls": "下载今日美图。仅限用作桌面壁纸。"
    }
}</pre>
![image](https://cloud.githubusercontent.com/assets/6056413/12696273/b2a20202-c798-11e5-8a6f-ab56404712ec.png)

**Comment by WenhaoWu** [comment]
Yes thanks for mentioning. Apparently bing server returns different json object based on user's location. However, base url section seems to be consistent nevertheless.
My Json respond:
[Json](https://raw.githubusercontent.com/WenhaoWu/BingWallpaper/master/Demo_Pics/Json.PNG)

Thanks again. It is beneficial to use url base.
